name: Waymark
options:
  bundleIdPrefix: io.atrandom
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  Waymark:
    type: application
    platform: macOS
    sources:
      - Waymark
    settings:
      base:
        CODE_SIGN_IDENTITY: "Waymark Dev"
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: io.atrandom.Waymark
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: targeted
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: Waymark/Info.plist
        CODE_SIGN_ENTITLEMENTS: Waymark/Waymark.entitlements
        COMBINE_HIDPI_IMAGES: true
      debug:
        ENABLE_HARDENED_RUNTIME: false
      release:
        ENABLE_HARDENED_RUNTIME: true
    entitlements:
      path: Waymark/Waymark.entitlements
      properties:
        com.apple.security.automation.apple-events: true
